language: go

go:
  - 1.8
addons:
  apt:
    packages:
      - python
      - python-pip
before_script:
  - echo $GOPATH
  - echo $PATH
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get -u google.golang.org/grpc
  - sudo pip install grpcio
