language: go

go:
  - 1.8
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - dh-autoreconf
before_script:
  - curl -L -O https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - unzip protoc-3.3.0-linux-x86_64.zip -d protoc && rm protoc-3.3.0-linux-x86_64.zip
  - export PATH=$(pwd)/protoc/bin:"${PATH}"
  - git clone https://github.com/grpc/grpc.git
  - cd grpc && git checkout tags/v1.4.1
  - git submodule update --init && make grpc_python_plugin
  - export PATH=$(pwd)/grpc-1.4.1/bin/opt:"${PATH}"
