py_library(
    name = "fake_display_driver_lib",
    srcs = [
        "fake_display_driver.py",
        "//proto:py",
    ],
)

py_binary(
    name = "fake_display_driver",
    srcs = [":fake_display_driver_lib"],
)

